//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourYearPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string prerequisites { get; set; }
        public string semester { get; set; }
        public int numOfPrerequisites { get; set; }
        public int Cancelled { get; set; }
        public string Type { get; set; }
        public string prereqIndex { get; set; }
    }
}
